### ISSUE TITLE
:bad substitution

### ISSUE THREAD

**Issue by qduong42** [pnuts93/cpp_class#1]
Hey Pietro,

I came across this resource today in the cpp-resources channel and it sounds very cool. Unfortunately, I get the following message when I use it: 

`/Users/qduong/.cargo/bin/cpp_class: line 6: '#ifndef '${fname^^}'_HPP'"\n"'#define '${fname^^}'_HPP'"\n\n"'#include <iostream>'"\n\n""class $fname""\n"'{'"\n""\tprivate:""\n\n""\tpublic:""\n"'\t\t'"$fname"'();'"\n"'\t\t'"$fname"'(const '"$fname"' &obj);'"\n"'\t\t'"$fname"'& operator=(const '"$fname"' &obj);'"\n"'\t\t~'"$fname"'();'"\n"'};'"\n\n"'#endif': bad substitution`

Name.hpp and Name.cpp are created but with nothing in them.

**Comment by pnuts93** [comment]
It is likely to be the syntax "${var^^}", which is a feature of Bash 4. I substituted it with a different syntax, try to see if this does the trick,

**Comment by qduong42** [comment]
Does the trick, this has been saving me so much time, thanks for your time!
